name: Test make and package contents consistency
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-make:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Check each app has a readme.txt
        run: |
          chmod +x ./.github/workflows/check_for_readme.sh
          ./.github/workflows/check_for_readme.sh
        shell: bash
      - name: Check root readme entries
        run: |
           chmod +x ./.github/workflows/check_root_readme_entries.sh 
           ./.github/workflows/check_root_readme_entries.sh 
        shell: bash       
      - name: Check if there is a new csclient.py
        run: |
          chmod +x ./.github/workflows/csclient_compare.sh
          ./.github/workflows/csclient_compare.sh
        shell: bash
      - name: Run make build and clean
        run: |
          chmod +x ./.github/workflows/builds.sh
          ./.github/workflows/builds.sh
        shell: bash
      - name: Tag
        if: github.event_name == 'push'
        uses: actions/github-script@v3
        with:
           github-token: ${{ github.token }}
           script: |
             github.git.deleteRef({
               owner: context.repo.owner,
               repo: context.repo.repo,
               ref: "tags/built_apps"
             })
             github.git.createRef({
               owner: context.repo.owner,
               repo: context.repo.repo,
               ref: "refs/tags/built_apps",
               sha: context.sha
             })
             setTimeout(() => { console.log("Done") }, 3000)
      - name: Publish
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: 'built_apps/*'
          tag_name: "built_apps"
          token: ${{ secrets.TOKEN }}
          body_path: ./built_apps/README.md
          name: "Built Apps"